
project_id = "jjdzrxfriezvfxjacche"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[storage]
file_size_limit = "50MiB"

[[storage.buckets]]
name = "scan_reports"
public = false
